# .streamlit/secrets.toml

# 1. Get your Google API key from Google AI Studio: https://aistudio.google.com/app/apikey
GOOGLE_API_KEY = "AIzaSyDO0e2AIi_VC3OosGneUuRGpmHPjDD7qIU"

# 2. Get your Cohere API key from: https://dashboard.cohere.com/api-keys
COHERE_API_KEY = "A9s79Hr9kso8kY24vZkAyT5if6wSCMG3UoRnX8PB"